services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: zhuyu-jellyfin
    network_mode: host
    volumes:
      - ./videos:/media/videos
      - ./infra/jellyfin-config:/config
      - ./infra/jellyfin-cache:/cache
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: zhuyu-tailscale
    network_mode: host
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:media
    volumes:
      - ./infra/tailscale-state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
